services:
  main:
    build: .
    command: sleep infinity
    working_dir: /workspace
    volumes:
      - ..:/workspace
    networks:
      - mitm-network
    cap_add:
      - NET_ADMIN
    privileged: true

  mitmweb:
    image: mitmproxy/mitmproxy:latest
    command: mitmweb --mode wireguard --web-host 0.0.0.0 --web-port 8081 --set web_password=password
    ports:
      - "8081:8081"  # mitmweb interface
      - "51820:51820/udp"  # WireGuard port
    networks:
      - mitm-network
    cap_add:
      - NET_ADMIN
    volumes:
      - mitmproxy-data:/home/mitmproxy/.mitmproxy

networks:
  mitm-network:
    driver: bridge

volumes:
  mitmproxy-data: